### ISSUE TITLE
add a timer / hide the configuration information

### ISSUE THREAD

**Issue by axel584** [svaponi/emdr-therapy-webapp#1]
Your app is very nice.
Could you add a timer to launch the EMDR for 20 seconde (or 1 minute) ?
Could you add a icon to hide (and show) the configuration tools) ?

Thank you very much,

Axel

**Comment by svaponi** [comment]
Hello @axel584, I implemented your change requests.
For now, use the spacebar to toggle controls.
If I find the time I'll add a help section with the all keyboard shortcuts. 
Let me know what you think.
